info:
  app:
    name: identity-service
    description: Identity microservice
    version: 1.0

spring:
  application:
    name: identity-service

eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9090
  # Enable response compression
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-responsize-size: 1024
  # Enable HTTP/2 support, if the current environment supports it
  http2:
    enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
